title: Octo
email: 
description: >- # this means to ignore newlines until ".
  Eating food.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
email: your-email@example.com

# Build settings
# theme: jekyll-theme-agency
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Customization
header_includes: "_includes/header.html"
footer_includes: "_includes/footer.html"

# Add these lines to enable header and footer includes
include:
  - _includes/header.html
  - _includes/footer.html