title: Octo
description: >- # this means to ignore newlines until ".
  Eating food.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://solid-octo-guide-mfhataavy-keith-trnkas-projects.vercel.app/" # the base hostname & protocol for your site
email: your-email@example.com

# Build settings
markdown: kramdown

# Customization
header_includes: "_includes/header.html"
footer_includes: "_includes/footer.html"

# Add these lines to enable header and footer includes
include:
  - _includes/header.html
  - _includes/footer.html