configure:
	bundle config set --local path vendor/bundle

npm-once:
	npm add postcss@latest tailwindcss@latest autoprefixer@latest cssnano@latest -D

install:
	bundle install
	npm install

serve:
	bundle exec jekyll serve --livereload